version: '3.3'

networks:
  shared-network:
    driver: bridge

services:

  zipkin:
    container_name: zipkin
    networks:
      - shared-network
    image: openzipkin/zipkin:2.11
    ports:
      - 9411:9411

  db:
    container_name: sales_db
    networks:
      - shared-network
    image: postgres:11.1-alpine
    ports:
      - 5432:5432

  sales-api:
    container_name: sales-api
    networks:
      - shared-network
    image: sales-api-amd64:1.0
    ports:
      - 3000:3000 # CRUD API
      - 4000:4000 # DEBUG API
    depends_on:
      - zipkin
      - db
      - kafka

  metrics:
    container_name: metrics
    networks:
      - shared-network
    image: metrics-amd64:1.0
    ports:
      - 3001:3001 # EXPVAR API
      - 4001:4001 # DEBUG API
    depends_on:
      - sales-api


  kafka:
    image: bitnami/kafka:latest
    ports:
      - 9092:9092
    environment:
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://:9092
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ZOOKEEPER_PROTOCOL: PLAINTEXT
    depends_on:
      - zookeeper
   
  zookeeper:
    image: bitnami/kafka:latest
    ports:
      - 2181:2181
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
      ZOO_LISTEN_ALLIPS_ENABLED: "yes"


  # zookeeper:
  #   hostname: zookeeper
  #   image: wurstmeister/zookeeper:3.4.6
  #   expose:
  #   - "2181"
  #   ports:
  #   - "2181:2181"
  
  # kafka:
  #   image: wurstmeister/kafka
  #   env_file:
  #   - kafka-variables.env
  #   depends_on:
  #   - zookeeper
  #   ports:
  #   - '9092:9092'
  #   - '8082:8082'
  #   - '8083:8083'
  #   restart: on-failure

    